# Generated by Django 4.1.4 on 2023-01-09 16:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0010_alter_program_application_end_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='program',
            name='business_unit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='program.businessunit'),
        ),
    ]
