# Generated by Django 4.1.4 on 2023-01-09 16:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0011_alter_program_business_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='program',
            name='business_unit',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='program.businessunit'),
        ),
    ]
