# Generated by Django 4.1.4 on 2023-01-09 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0012_alter_program_business_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='program',
            name='application_end_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='program',
            name='application_start_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='program',
            name='end_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='program',
            name='start_time',
            field=models.DateTimeField(null=True),
        ),
    ]
